# database credentials
database_user: "SpringClinicAPI"
database_password: "{{ lookup('file', 'credentials/SpringClinicAPI/mysqlpassword') }}"

resource_group: wuslab2

vms: 
  - frontend
  - backend
  - database

# ports
frontend_port: 8080
backend_port: 8080
database_port: 3306

# host addresses
frontend_host: 51.11.143.10
backend_host: 20.49.202.212
database_host: 20.49.204.9

# private net addresses
frontend_priv_ip: 10.0.1.5
backend_priv_ip: 10.0.2.5
database_priv_ip: 10.0.3.5
