setup: 3

# You can setup where each service will be deployed
frontend_host: vm1
backend_host: vm1
db_default_host: vm1
db_master_host: vm1
db_slave_host: vm1

# ports
frontend_port: 8080
backend_port: 8081
db_default_port: 3306
db_master_port: 3306
db_slave_port: 3312

resource_group: wuslab2

# virtual machines addresses
vm1:
  address: 51.145.64.21
  priv_ip: 10.0.1.5
vm2:
  address: 51.145.64.163
  priv_ip: 10.0.2.5
vm3:
  address: 20.77.103.37
  priv_ip: 10.0.3.5

# database credentials
database_user: "api"
database_password: "{{ lookup('file', 'credentials/SpringClinicAPI/mysqlpassword') }}"
