setup: 4

# You can setup where each service will be deployed
frontend_host: vm1
back_default_host: vm1
back_master_host: vm1
back_slave_host: vm1
db_default_host: vm1
db_master_host: vm1
db_slave_host: vm1
ngnix_host: vm1

# ports
frontend_port: 8080
back_default_port: 8081
back_master_port: 8091
back_slave_port: 8092
db_default_port: 3306
db_master_port: 3306
db_slave_port: 3312
ngnix_port: 8090

resource_group: wuslab2

# virtual machines addresses
vm1:
  address: 51.145.80.110
  priv_ip: 10.0.1.5
vm2:
  address: 20.0.240.196
  priv_ip: 10.0.2.5
vm3:
  address: 51.145.82.255
  priv_ip: 10.0.3.5

# database credentials
database_user: "api"
database_password: "{{ lookup('file', 'credentials/SpringClinicAPI/mysqlpassword') }}"
