- name: Pet clinic deployment
  hosts: localhost
  vars_files: config.yml
  vars:
    dir: "{{ playbook_dir }}"
  tasks:
    # - name: Create virtual machines
    #   ansible.builtin.shell:
    #     chdir: "{{ dir }}/vm_scripts"
    #     cmd: bash deploy.sh config1.json
    #   register: output
    # - ansible.builtin.debug:
    #     msg: "{{ output }}"
    - name: Get virtual machines public ip's
      ansible.builtin.shell:
        cmd: az network public-ip show --resource-group "{{ resource_group }}"  --name "{{ item }}"  --query "ipAddress" --output tsv
      loop: "{{ groups['wuslab2'] }}"
      register: echo
    - name: Save virtual machines public ip's in config.yml
      ansible.builtin.replace:
        path: "{{ playbook_dir }}/config.yml"
        regexp: "^{{ item.item }}:.*\n *address:.*"
        replace: "{{ item.item }}:\n  address: {{ item.stdout }}"
      loop: "{{ echo.results }}"
    - name: Save virtual machines public ip's in inventory.yaml
      ansible.builtin.replace:
        path: "{{ playbook_dir }}/inventory.yaml"
        regexp: "^ *{{ item.item }}:\n *ansible_host.+"
        replace: "    {{ item.item }}:\n      ansible_host: {{ item.stdout }}"
      loop: "{{ echo.results }}"

- name: Setting up default database
  hosts: "{{ db_default_host }}"
  vars_files: config.yml
  vars:
    type: default
  become: true
  roles:
    - role: database
      when: setup == 1

- name: Setting up master database
  hosts: "{{ db_master_host }}"
  vars_files: config.yml
  vars:
    type: master
  become: true
  roles:
    - role: database
      when: setup == 3 or setup == 4

- name: Setting up slave database
  hosts: "{{ db_slave_host }}"
  vars_files: config.yml
  vars:
    type: slave
  become: true
  roles:
    - role: database
      when: setup == 3 or setup == 4

- name: Deploying backend
  hosts: "{{ backend_host }}"
  vars_files: config.yml
  become: true
  roles:
    - backend

- name: Deploying frontend
  hosts: "{{ frontend_host }}"
  vars_files: config.yml
  become: true
  roles:
    - frontend
