- name: Updating apt-get
  ansible.builtin.shell:
    cmd: sudo apt-get update
  register: output
- ansible.builtin.debug:
    msg: "{{ output.stdout_lines }}"
- name: Installing Docker
  ansible.builtin.shell:
    cmd: sudo apt-get install docker.io -y
  register: output
- ansible.builtin.debug:
    msg: "{{ output }}"
- name: Create database directory
  ansible.builtin.file:
    path: /database
    state: directory
    mode: '0755'
- name: Copy Dockerfile
  ansible.builtin.copy:
    src: Dockerfile
    dest: /database/Dockerfile
- name: Change database username in Dockerfile
  ansible.builtin.replace:
    path: /database/Dockerfile
    regexp: '^.*MYSQL_USER=".*"'
    replace: '    MYSQL_USER="{{ database_user }}"'
- name: Change database password in Dockerfile
  ansible.builtin.replace:
    path: /database/Dockerfile
    regexp: '^.*MYSQL_PASSWORD=".*"'
    replace: '    MYSQL_PASSWORD="{{ database_password }}"'
- name: Build docker image
  community.docker.docker_image:
    build:
      path: /database
    name: petclinic-mysql:latest
    source: build
    force_tag: true
    force_source: true
- name: Remove docker container
  community.docker.docker_container:
    name: mysql
    state: absent
- name: Run docker container
  community.docker.docker_container:
    name: mysql
    image: petclinic-mysql:latest
    published_ports:
      - "{{ database_port }}:3306"
    
